feat: home page layout
vetalapo/eCommerce pull request #115
Opened 2024-06-12 02:03 UTC by valeryiay

1. Task: [Implementing a main page](https://github.com/users/vetalapo/projects/3/views/1?pane=issue&itemId=67059890)
2. Screenshot:
![Screenshot 2024-06-12 034537](https://github.com/vetalapo/eCommerce/assets/97828680/be55b4dc-7fad-4379-a982-023956a53a7b)

3. Here's what to think about:
- [ ] Routing: check out
- [ ] Breadcrumbs
- [ ] Buttons: adding items to their cart, signing up, go to the Detailed Page
- [ ] Show Off Popular Stuff: Put the cool and popular stuff front and center. Show pictures and short descriptions to catch people's interest and make them want to see more.
- [ ] Search bar product.description?.["en-GB"]
- [ ] Product Categories from commercetoolsApi
- [ ] Special Offers (discont)
- [x] Responsive Design: layout is responsive and adapts seamlessly to various screen sizes and devices. ++ optimize images
- [ ] fast loading, smooth
- [ ] customer reviews and ratings for products directly into the main page, highlight positive reviews
4. This is what our home page might look like.  Logic and routing not added, can be developed

2024-06-12 11:14 UTC, vetalapo requested changes
It's great to have something on the home page. Could you please also make categories pictures to be the same size?
It's looking crooked at the moment.

![image](https://github.com/vetalapo/eCommerce/assets/2862871/91d179bc-4749-402d-9d43-072ef2778da3)

2024-06-12 11:14 UTC, vetalapo commented on src/views/HomeView.vue
> +    .catalog-container {
This container is no a catalog. Please think of a better name reflecting the container's purpose.

2024-06-12 11:14 UTC, vetalapo commented on src/views/HomeView.vue
> -        <TheWelcome />
We probably do not need "TheWelcome" component at all, you could delete it also.

2024-06-13 15:02 UTC, JoMarianek commented
Updated the images to look more uniform, let me know if you prefer all images to be vertical.

2024-06-13 17:03 UTC, vetalapo requested changes
I would suggest cards to be like this:
![image](https://github.com/vetalapo/eCommerce/assets/2862871/2fc5a727-07f4-4cba-b85f-fed879c5cbab)

Without spaces in card because of horizontal pictures.
Spaces don't look attractive

![image](https://github.com/vetalapo/eCommerce/assets/2862871/be84021b-44a6-447e-9ca0-bd11eddc4b61)

2024-06-13 23:11 UTC, vetalapo requested changes
TheWelcome component, its test and entire components folder have to be removed as it's not used by anything else anymore.

2024-06-13 23:22 UTC, vetalapo approved these changes
Job nicely done!

2024-06-13 23:32 UTC, merged