feat: fetch and display cart items
vetalapo/eCommerce pull request #120
Opened 2024-06-14 12:34 UTC by valeryiay

1. Task: [RSS-ECOMM-4_10: Fetch and Display Cart Items Using commercetools API](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/eCommerce-Application/Sprints/Sprint4/RSS-ECOMM-4_10.md)
2. Screenshot:
![Screenshot 2024-06-14 142934](https://github.com/vetalapo/eCommerce/assets/97828680/a4213a14-24c3-4978-869c-080918887568)

3. Change description

- [x]  Make use of the commercetools API to fetch the list of items present in the user's shopping cart.
- [x] Present this list of items on the user interface, making sure that the name, image, and individual price, as well as the total cost for all quantities of each item, are included.

5. Change rationale
To provide a detailed summary of items in the shopping cart, we'll use the commercetools API to fetch and display items.

2024-06-14 12:49 UTC, vetalapo requested changes
Everything you need should be already in cart in local storage. There's no need to go fetch data at this point, only if you update something.

2024-06-14 12:49 UTC, vetalapo commented on src/services/commercetoolsApi.ts
Please revert changes to this file.

2024-06-14 12:49 UTC, vetalapo commented on src/views/BasketView.vue
> +    async mounted() {
Please remove everything in mounted()

2024-06-14 12:49 UTC, vetalapo commented on src/views/BasketView.vue
> +export default defineComponent({
You don't have to define a component. Please make it consistent with existing views.

2024-06-14 15:15 UTC, vetalapo requested changes
Also please include a screenshot with cart items.

2024-06-14 15:15 UTC, vetalapo commented on .env.example
Why is this file removed? Cancel this change.

2024-06-14 15:15 UTC, vetalapo commented on src/views/BasketView.vue
> +            async fetchCartItems() {
There is no need to fetch data and store it in local storage as local storage already contains all data you might need for this task.

2024-06-14 17:27 UTC, vetalapo requested changes
Please include an additional screenshot in PR description of the basket page with some items displayed. The task says it should be displayed, just want to make sure everything works.

2024-06-14 17:27 UTC, vetalapo commented on .env.example
Discard changes to this file.

2024-06-14 17:27 UTC, vetalapo commented on src/views/BasketView.vue
> +            const storedCartDataString = localStorage.getItem("cartData");
There is no need to go to the local storage, AuthStore already has it ready to use.
Also please remove all this logic from data, it doesn't belong here.

2024-06-14 20:50 UTC, valeryiay commented on .env.example
the file was accidentally deleted and then restored

2024-06-14 20:50 UTC, valeryiay commented on src/views/BasketView.vue
> +            const storedCartDataString = localStorage.getItem("cartData");
Thank you!

2024-06-18 16:38 UTC, vetalapo commented
Sorry, I'll have to close the PR. Making it work will be incredibly hard, considering time constraints we got.

2024-06-18 16:38 UTC, closed without merging