Rss ecomm 02 09
vetalapo/eCommerce pull request #33
Opened 2024-05-19 00:34 UTC by JoMarianek

1. Task: [link](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/eCommerce-Application/Sprints/Sprint2/RSS-ECOMM-2_09.md)
2. Screenshot:
3. Change description: implemented registration page with required validation and error messages. I haven't implemented responsive design for small screens.
4. Change rationale

2024-05-19 11:41 UTC, vetalapo requested changes

2024-05-19 11:41 UTC, vetalapo commented on package.json
Please revert changes to this file.

2024-05-19 11:41 UTC, vetalapo commented on src/data/countries.ts
We need our own source of countries. Please remove this file.

2024-05-19 11:41 UTC, vetalapo commented on src/validation/registValidationSchema.ts
Please remove this file. We need only what vuetify provides. No need to complicates things.

2024-05-19 11:41 UTC, vetalapo commented on src/views/RegistrationView.vue
> +                minEight: (value: string) => value.length >= 8 || "Min 8 characters",
Why there is two "minEight" and "minLength"? Please leave just one.

2024-05-19 11:41 UTC, vetalapo commented on src/views/RegistrationView.vue
> +            rules: {
We have a lot of duplicating rules for registration and login pages. Maybe we could extract these rules in a separate class and import them?

2024-05-19 11:41 UTC, vetalapo commented on src/views/RegistrationView.vue
> +                }
Starting line 30 please make indents and spaces between blocks so it is easier to read. Maybe extracting it to a function would be better?

2024-05-19 11:41 UTC, vetalapo commented on src/views/RegistrationView.vue
> +                <h2 class="text-center pa-4" :style="{ color: '#099A9A' }">Sign up to get access to exclusive features and benefits.</h2>
Please don't assign styles like this. :style in Vue is for reactive changes. What you did could be put just in styles section.

2024-05-19 11:41 UTC, vetalapo commented on src/views/RegistrationView.vue
> +                        <h3 class="text-center pa-6" :style="{ color: '#099A9A' }">Sign up to get goods <br><span :style="{ fontWeight: 300}">you love</span></h3>
Please don't assign styles like this. :style in Vue is for reactive changes. What you did could be put just in styles section.

2024-05-19 11:41 UTC, vetalapo commented on src/views/RegistrationView.vue
> +         url("../assets/img/background.png") center/cover no-repeat;
Please indent with 4 white spaces.

2024-05-19 11:41 UTC, vetalapo commented on src/views/RegistrationView.vue
> +                            href="#"
Please put "/login" in href. We already have the login page.

2024-05-19 11:41 UTC, vetalapo commented on package.json
> +        "@vue/cli-plugin-typescript": "^5.0.8",
If you including the plugin, I think you'll also have write rules for it.

2024-05-19 11:41 UTC, vetalapo commented on src/assets/img/background.png
It looks like left and bottom have empty areas? Is it per design?

2024-05-19 11:41 UTC, vetalapo commented on src/views/RegistrationView.vue
> +            password: '',
Please use double quotes "" for values

2024-05-19 11:43 UTC, vetalapo requested changes
Please add screenshot of the page in the PR

2024-05-20 11:31 UTC, JoMarianek commented on package.json
> +        "@vue/cli-plugin-typescript": "^5.0.8",
Ok, I removed it

2024-05-20 16:18 UTC, JoMarianek commented
@vetalapo Implemented all requested changes, could you please take a look and approve?

2024-05-20 17:03 UTC, JoMarianek commented
@vetalapo implemented changes

2024-05-20 17:28 UTC, vetalapo requested changes
Please take a look at the last couple of things. It is almost ready to merg.

2024-05-20 17:28 UTC, vetalapo commented on src/views/LoginView.vue
> +            commonRules: ValidationRules,
Missed this, please don't leave trailing commas.

2024-05-20 17:28 UTC, vetalapo commented on src/views/RegistrationView.vue
> +                return age >= 13 || "You must be at least 13 years old.";
Please indent with 4 spaces this too.

2024-05-20 20:16 UTC, JoMarianek commented
@vetalapo implemented changes

2024-05-20 20:18 UTC, vetalapo approved these changes

2024-05-20 20:19 UTC, merged