Rss ecomm 3 14
vetalapo/eCommerce pull request #70
Opened 2024-06-01 19:30 UTC by vetalapo

1. Task: [link](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/eCommerce-Application/Sprints/Sprint3/RSS-ECOMM-3_14.md)
2. Screenshot:
![image](https://github.com/vetalapo/eCommerce/assets/2862871/784c5657-7f86-4eeb-af25-7654c9d02fa6)

3. Change description:

Made user profile page which displays user's full name, birthday, addresses (regular, types, and default)
Updated routing so only logged in users can see their profiles.

2024-06-01 21:25 UTC, valeryiay requested changes
I've added a few comments about formatting, but the PR looks good overall.

2024-06-01 22:12 UTC, vetalapo commented on src/views/ProfileView.vue
> +                            return country.title
Good catch. 👌

2024-06-01 22:16 UTC, vetalapo commented on src/views/ProfileView.vue
> +                            const isShippingAddress = this.authStore?.user?.user?.shippingAddressIds.includes(item.id);
72, 79 - it doesn't matter, but ok.

What's wrong with 74, 81, 83?

2024-06-01 22:16 UTC, vetalapo commented on src/views/ProfileView.vue
> +    }
👍

2024-06-01 22:18 UTC, vetalapo commented on src/views/ProfileView.vue
> +                                    >
It's self closing. And it's actually a bad practice to close this tags as /> in HTML
https://jakearchibald.com/2023/against-self-closing-tags-in-html/

2024-06-01 22:21 UTC, vetalapo commented on src/views/ProfileView.vue
> +                            <h2 class="text-h4 font-weight-black">{{ authStore?.user?.user?.firstName }} {{authStore?.user?.user?.lastName}}</h2>
125, 164? What's wrong? They look okay.

2024-06-01 22:25 UTC, vetalapo commented on src/views/ProfileView.vue
> +        border-radius: 5%!important;
It's doesn't help with anything but ok 👍

2024-06-01 22:26 UTC, vetalapo commented on src/views/RootView.vue
>      }
👍

2024-06-01 22:27 UTC, vetalapo commented on src/views/RootView.vue
> +                                    >
It's self closing. And it's actually a bad practice to close this tags as /> in HTML
https://jakearchibald.com/2023/against-self-closing-tags-in-html/

2024-06-01 22:28 UTC, vetalapo commented on src/views/RootView.vue
>          margin-right: 250px;
👍

2024-06-01 22:29 UTC, vetalapo commented on src/views/__tests__/ProfileView.spec.ts
> +import { useAuthStore } from "@/store";
It'll be needed for the next PR. I think I'm going to leave it there for now.

2024-06-02 07:40 UTC, valeryiay approved these changes
looks good. thank you!

2024-06-02 07:40 UTC, valeryiay commented on src/views/RegistrationView.vue
double quotes on 80 line

2024-06-02 14:04 UTC, JoMarianek reviewed
Looks good good, thank you!

2024-06-02 16:04 UTC, vetalapo commented on src/views/RegistrationView.vue
👍

2024-06-02 16:05 UTC, merged